// HIVY ANNIVERSARY - Anniversary-Only Service Categories
// This file contains all anniversary-focused keyword pages

import { ServiceCategory } from './ffc-config';

// ==================== ANNIVERSARY-ONLY SERVICE CATEGORIES ====================
export const anniversaryServiceCategories: ServiceCategory[] = [
  {
    slug: "anniversary-celebration",
    name: "Anniversary Celebration",
    emoji: "💑",
    description: "Celebrate every year of your love journey with elegant anniversary dinners, romantic decorations, and intimate private celebrations at Surat's premier anniversary venue.",
    metaTitle: "Anniversary Celebration in Surat | HIVY Anniversary",
    metaDescription: "Plan the perfect anniversary celebration in Surat at HIVY Anniversary. Romantic rooftop dinners, elegant decorations, and intimate moments for couples celebrating their love.",
    keywords: [
      // EXISTING ANNIVERSARY KEYWORDS (KEEP)
      { slug: "anniversary-dinner-surat", title: "Anniversary Dinner", h1: "Romantic Anniversary Dinner in Surat", metaTitle: "Anniversary Dinner Surat | Romantic Restaurant", metaDescription: "Book a romantic anniversary dinner in Surat at HIVY Anniversary. Candlelight setup, special decorations, and intimate dining for couples." },
      { slug: "anniversary-surprise-for-husband-surat", title: "Anniversary Surprise for Husband", h1: "Anniversary Surprise for Husband in Surat", metaTitle: "Anniversary Surprise for Husband Surat | Special Setup", metaDescription: "Plan a special anniversary surprise for your husband in Surat with romantic decorations and intimate celebration at HIVY Anniversary." },
      { slug: "anniversary-surprise-for-wife-surat", title: "Anniversary Surprise for Wife", h1: "Anniversary Surprise for Wife in Surat", metaTitle: "Anniversary Surprise for Wife Surat | Make Her Special", metaDescription: "Create a beautiful anniversary surprise for your wife in Surat with elegant decorations and romantic ambiance at HIVY Anniversary." },
      { slug: "first-anniversary-celebration-surat", title: "First Anniversary Celebration", h1: "First Anniversary Celebration in Surat", metaTitle: "First Anniversary Celebration Surat | Paper Anniversary", metaDescription: "Celebrate your first paper anniversary in Surat with a special romantic setup at HIVY Anniversary rooftop venue." },
      { slug: "wedding-anniversary-party-surat", title: "Wedding Anniversary Party", h1: "Wedding Anniversary Party in Surat", metaTitle: "Wedding Anniversary Party Surat | Private Venue", metaDescription: "Host a memorable wedding anniversary party in Surat with private venue and romantic decorations at HIVY Anniversary." },
      { slug: "anniversary-decoration-surat", title: "Anniversary Decoration", h1: "Anniversary Decoration in Surat", metaTitle: "Anniversary Decoration Surat | Romantic Setup", metaDescription: "Beautiful anniversary decoration in Surat with flowers, balloons, and romantic themes at HIVY Anniversary celebration venue." },
      { slug: "anniversary-celebration-ideas-surat", title: "Anniversary Celebration Ideas", h1: "Best Anniversary Celebration Ideas in Surat", metaTitle: "Anniversary Celebration Ideas Surat | Creative Plans", metaDescription: "Find creative anniversary celebration ideas in Surat. From candlelight dinners to rooftop surprises at HIVY Anniversary." },
      { slug: "romantic-anniversary-date-surat", title: "Romantic Anniversary Date", h1: "Romantic Anniversary Date in Surat", metaTitle: "Romantic Anniversary Date Surat | Perfect Evening", metaDescription: "Plan a romantic anniversary date in Surat with candlelight dinner and beautiful decorations at HIVY Anniversary." },
      { slug: "anniversary-venues-surat", title: "Anniversary Venues", h1: "Best Anniversary Venues in Surat", metaTitle: "Anniversary Venues Surat | Couple-Friendly", metaDescription: "Discover the best anniversary venues in Surat for couples. HIVY Anniversary offers private rooftop celebrations." },
      { slug: "anniversary-restaurants-surat", title: "Anniversary Restaurants", h1: "Best Anniversary Restaurants in Surat", metaTitle: "Anniversary Restaurants Surat | Romantic Dining", metaDescription: "Find the best anniversary restaurants in Surat for romantic dining. HIVY Anniversary offers candlelight dinners." },
      { slug: "surprise-anniversary-party-surat", title: "Surprise Anniversary Party", h1: "Surprise Anniversary Party in Surat", metaTitle: "Surprise Anniversary Party Surat | Secret Celebration", metaDescription: "Plan a surprise anniversary party in Surat with secret setup and romantic decorations at HIVY Anniversary." },
      { slug: "anniversary-planners-surat", title: "Anniversary Planners", h1: "Anniversary Planners in Surat", metaTitle: "Anniversary Planners Surat | Professional Service", metaDescription: "Professional anniversary planners in Surat. We handle everything from decorations to dining at HIVY Anniversary." },
      { slug: "25th-anniversary-celebration-surat", title: "25th Anniversary Celebration", h1: "25th Wedding Anniversary Celebration in Surat", metaTitle: "25th Anniversary Celebration Surat | Silver Jubilee", metaDescription: "Celebrate your silver jubilee 25th anniversary in Surat with special decorations and romantic setup at HIVY Anniversary." },
      { slug: "10th-anniversary-celebration-surat", title: "10th Anniversary Celebration", h1: "10th Anniversary Celebration in Surat", metaTitle: "10th Anniversary Celebration Surat | Decade of Love", metaDescription: "Mark a decade of love with 10th anniversary celebration in Surat at HIVY Anniversary venue." },
      { slug: "anniversary-date-night-surat", title: "Anniversary Date Night", h1: "Anniversary Date Night in Surat", metaTitle: "Anniversary Date Night Surat | Romantic Evening", metaDescription: "Plan a special anniversary date night in Surat with candlelight dinner and romantic music at HIVY Anniversary." },
      
      // NEW 20 ANNIVERSARY KEYWORDS
      { slug: "2nd-anniversary-celebration-surat", title: "2nd Anniversary Celebration", h1: "2nd Anniversary Celebration in Surat", metaTitle: "2nd Anniversary Celebration in Surat | HIVY", metaDescription: "Celebrate your 2nd wedding anniversary in Surat with romantic dinners, decorations & surprises. Book the perfect cotton anniversary experience at HIVY." },
      { slug: "5th-anniversary-celebration-surat", title: "5th Anniversary Celebration", h1: "5th Anniversary Celebration in Surat", metaTitle: "5th Anniversary Celebration in Surat | HIVY", metaDescription: "Plan a memorable 5th wedding anniversary in Surat. Wood anniversary celebration packages with romantic setups, private dining & couple activities." },
      { slug: "15th-anniversary-celebration-surat", title: "15th Anniversary Celebration", h1: "15th Anniversary Celebration in Surat", metaTitle: "15th Anniversary Celebration Surat | HIVY", metaDescription: "Celebrate 15 years of love with a crystal anniversary celebration in Surat. Romantic venues, special decorations & unforgettable experiences await." },
      { slug: "20th-anniversary-celebration-surat", title: "20th Anniversary Celebration", h1: "20th Anniversary Celebration in Surat", metaTitle: "20th Anniversary Celebration Surat | HIVY", metaDescription: "Mark 20 years of togetherness with a china anniversary celebration in Surat. Premium venues, elegant decor & personalized anniversary packages." },
      { slug: "50th-golden-anniversary-surat", title: "50th Golden Anniversary", h1: "50th Golden Anniversary Celebration in Surat", metaTitle: "50th Golden Anniversary Celebration Surat", metaDescription: "Plan a grand 50th golden wedding anniversary celebration in Surat. Luxury venues, family gatherings & memorable golden jubilee party arrangements." },
      { slug: "silver-anniversary-celebration-surat", title: "Silver Anniversary Celebration", h1: "Silver Anniversary Celebration in Surat", metaTitle: "Silver Anniversary Celebration Surat | HIVY", metaDescription: "Celebrate 25 years of marriage with a silver anniversary party in Surat. Elegant silver-themed decorations, venues & celebration packages available." },
      { slug: "diamond-anniversary-celebration-surat", title: "Diamond Anniversary Celebration", h1: "Diamond Anniversary Celebration in Surat", metaTitle: "Diamond Anniversary Celebration Surat", metaDescription: "Honor 60 years of love with a diamond anniversary celebration in Surat. Grand family gatherings, premium venues & unforgettable diamond jubilee events." },
      { slug: "rooftop-anniversary-dinner-surat", title: "Rooftop Anniversary Dinner", h1: "Rooftop Anniversary Dinner in Surat", metaTitle: "Rooftop Anniversary Dinner in Surat | HIVY", metaDescription: "Enjoy a romantic rooftop anniversary dinner under the stars in Surat. Private dining, city views & customized anniversary setups for couples." },
      { slug: "private-anniversary-celebration-surat", title: "Private Anniversary Celebration", h1: "Private Anniversary Celebration in Surat", metaTitle: "Private Anniversary Celebration Surat", metaDescription: "Plan an intimate private anniversary celebration in Surat. Exclusive venues, personalized setups & romantic experiences just for two. Book now!" },
      { slug: "luxury-anniversary-celebration-surat", title: "Luxury Anniversary Celebration", h1: "Luxury Anniversary Celebration in Surat", metaTitle: "Luxury Anniversary Celebration Surat | HIVY", metaDescription: "Experience a premium luxury anniversary celebration in Surat. 5-star venues, gourmet dining, luxury decor & VIP treatment for your special day." },
      { slug: "intimate-anniversary-dinner-surat", title: "Intimate Anniversary Dinner", h1: "Intimate Anniversary Dinner in Surat", metaTitle: "Intimate Anniversary Dinner in Surat | HIVY", metaDescription: "Celebrate your anniversary with an intimate dinner for two in Surat. Cozy settings, romantic ambiance & personalized couple dining experiences." },
      { slug: "anniversary-celebration-for-parents-surat", title: "Anniversary Celebration for Parents", h1: "Anniversary Celebration for Parents in Surat", metaTitle: "Anniversary Celebration for Parents Surat", metaDescription: "Surprise your parents with a beautiful anniversary celebration in Surat. Family gathering venues, thoughtful decorations & memorable party planning." },
      { slug: "anniversary-surprise-for-in-laws-surat", title: "Anniversary Surprise for In-Laws", h1: "Anniversary Surprise for In-Laws in Surat", metaTitle: "Anniversary Surprise for In-Laws Surat | HIVY", metaDescription: "Plan a heartfelt anniversary surprise for your in-laws in Surat. Elegant celebrations, family-friendly venues & respectful anniversary arrangements." },
      { slug: "couple-anniversary-getaway-surat", title: "Couple Anniversary Getaway", h1: "Couple Anniversary Getaway in Surat", metaTitle: "Couple Anniversary Getaway in Surat | HIVY", metaDescription: "Escape for a romantic couple anniversary getaway in Surat. Weekend packages, staycation deals & memorable experiences for celebrating your love." },
      { slug: "anniversary-photoshoot-surat", title: "Anniversary Photoshoot", h1: "Anniversary Photoshoot in Surat", metaTitle: "Anniversary Photoshoot in Surat | HIVY", metaDescription: "Capture your love with a professional anniversary photoshoot in Surat. Romantic locations, expert photographers & beautiful couple photography packages." },
      { slug: "anniversary-weekend-celebration-surat", title: "Anniversary Weekend Celebration", h1: "Anniversary Weekend Celebration in Surat", metaTitle: "Anniversary Weekend Celebration Surat", metaDescription: "Plan a complete anniversary weekend celebration in Surat. Multi-day packages with dinner, activities, photoshoots & romantic experiences for couples." },
      { slug: "anniversary-night-out-surat", title: "Anniversary Night Out", h1: "Anniversary Night Out in Surat", metaTitle: "Anniversary Night Out in Surat | HIVY", metaDescription: "Plan the perfect anniversary night out in Surat. Dinner reservations, entertainment options & romantic evening experiences for celebrating couples." },
      { slug: "budget-anniversary-celebration-surat", title: "Budget Anniversary Celebration", h1: "Budget Anniversary Celebration in Surat", metaTitle: "Budget Anniversary Celebration Surat | HIVY", metaDescription: "Celebrate your anniversary on a budget in Surat. Affordable romantic setups, pocket-friendly venues & memorable experiences without breaking the bank." },
      { slug: "outdoor-anniversary-celebration-surat", title: "Outdoor Anniversary Celebration", h1: "Outdoor Anniversary Celebration in Surat", metaTitle: "Outdoor Anniversary Celebration Surat", metaDescription: "Celebrate your anniversary outdoors in Surat. Garden venues, open-air dining, nature settings & beautiful al fresco anniversary celebration packages." },
      { slug: "last-minute-anniversary-plans-surat", title: "Last Minute Anniversary Plans", h1: "Last Minute Anniversary Plans in Surat", metaTitle: "Last Minute Anniversary Plans Surat | HIVY", metaDescription: "Forgot your anniversary? Book last minute anniversary plans in Surat today! Same-day bookings, quick setups & instant romantic celebration arrangements." }
    ]
  }
];

// Helper function to get all anniversary keywords
export function getAllAnniversaryKeywords() {
  return anniversaryServiceCategories[0].keywords;
}

// Helper function to get keyword by slug
export function getAnniversaryKeywordBySlug(slug: string) {
  return anniversaryServiceCategories[0].keywords.find(k => k.slug === slug);
}
